module.exports = async () => {
  return {
    globals: {
      'ts-jest': {
        tsConfig: 'tsconfig.json',
        diagnostics: true,
      },
      NODE_ENV: 'test',
    },
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
    verbose: true,
    rootDir: './src',
    preset: 'ts-jest',
    moduleNameMapper: {
      '^types/(.*)$': '<rootDir>/types/$1',
      '^store/(.*)$': '<rootDir>/store/$1',
      '^hkclient$': '<rootDir>/hkclient',
      '^hkclient/(.*)$': '<rootDir>/hkclient/$1',
      '^constants$': '<rootDir>/constants',
      '^constants/(.*)$': '<rootDir>/constants/$1',
      '^utils$': '<rootDir>/utils',
      '^utils/(.*)$': '<rootDir>/utils/$1',
      '^testlib$': '<rootDir>/testlib',
      '^testlib/(.*)$': '<rootDir>/testlib/$1',
      '^action-types$': '<rootDir>/action-types',
      '^action-types/(.*)$': '<rootDir>/action-types/$1',
      '^actions$': '<rootDir>/actions',
      '^actions/(.*)$': '<rootDir>/actions/$1',
      '^reducers$': '<rootDir>/reducers',
      '^reducers/(.*)$': '<rootDir>/reducers/$1',
      '^selectors$': '<rootDir>/selectors',
      '^selectors/(.*)$': '<rootDir>/selectors/$1',
      '^hkmodules$': '<rootDir>/modules',
      '^hkmodules/(.*)$': '<rootDir>/modules/$1',
      '^saga-modular$': '<rootDir>/redux/saga-modular',
      '^saga-modular/(.*)$': '<rootDir>/redux/saga-modular/$1',
      '^hksagas$': '<rootDir>/sagas',
      '^hksagas/(.*)$': '<rootDir>/sagas/$1',
      '^hkreducers$': '<rootDir>/reducers',
      '^hkreducers/(.*)$': '<rootDir>/reducers/$1',
      '^hkredux$': '<rootDir>/hkredux',
      '^hkredux/(.*)$': '<rootDir>/hkredux/$1',
    },
  }
}
